package templates

// SwaggerTemplatePrefix 资源pb文件模板
var SwaggerTemplatePrefix = "// Code generated by lucas. DO NOT EDIT.\n" +
	"// Source: \n" +
	"\n" +
	"package service \n" +
	"\n" +
	"// SwaggerPath defines swagger server path\n" +
	"var SwaggerPath = \"/api/v1/{{.LowerCaseObjectsName}}/openapi/swagger.json\"\n" +
	"\n" +
	"// SwaggerJSON is a copy of generated.swagger.json\n" +
	"var SwaggerJSON = `"

// SwaggerTemplateSuffix 资源pb文件模板
var SwaggerTemplateSuffix = "`"
